name: Build then run CI Chains

on: [push]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    # Install and setup go
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    # build gaiad/gaiacli
    - name: checkout gaia
      uses: actions/checkout@v2
      with:
        repository: cosmos/gaia
        ref: refs/heads/ibc-alpha
    # Setup Cache
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-gaia-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-gaia-go-
    - name: build binary
      run: make build

    # upload gaiacli binary
    - name: upload gaiacli binary
      uses: actions/upload-artifact@v1
      with:
        name: gaiacli
        path: ./build/gaiacli

    # upload gaiad binary
    - name: upload gaiad binary
      uses: actions/upload-artifact@v1
      with:
        name: gaiad
        path: ./build/gaiad

    # checkout relayer
    - name: checkout relayer
      uses: actions/checkout@v2
    
    # Setup Cache
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-relayer-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-relayer-go-
    
    # build binary
    - name: build binary and move to upload location
      run: make build

    # upload resulting binaries
    - name: upload binaries
      uses: actions/upload-artifact@v1
      with:
        name: relayer
        path: ./build/relayer

  test:
    name: test-liveness
    needs: build
    runs-on: ubuntu-latest
    steps:

    # Checkout the relayer repo
    - name: Checkout relayer
      uses: actions/checkout@v2

    # Make binary directory
    - name: create directory
      run: mkdir -p /tmp/build
    
    # Install jq
    - name: Install jq
      run: sudo apt install jq -y

    # Download gaiad binary
    - name: download gaiad
      uses: actions/download-artifact@v1
      with:
        name: gaiad
        path: /tmp/build

    # Download gaiacli binary
    - name: download gaiacli
      uses: actions/download-artifact@v1
      with:
        name: gaiacli
        path: /tmp/build

    # Download binaries
    - name: download relayer
      uses: actions/download-artifact@v1
      with:
        name: relayer  
        path: /tmp/build

    # Make binaries executable
    - name: chmod
      run: chmod +x /tmp/build/*

    # Run the ci-chains.sh test 
    - name: Run ci-chains check
      run: |
        ./ci-chains.sh

