name: TESTING - interchaintest

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  events:
    runs-on: self-hosted
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-events

  legacy:
    runs-on: self-hosted
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-legacy

  multiple-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-multiple

  misbehaviour:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-misbehaviour

  fee-middleware:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-fee-middleware

  fee-grant:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-fee-grant

  scenarios-client:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-scenario-client
      
  scenarios-ica:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-scenario-ica
      
  scenarios-interchainaccounts:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-scenario-interchainaccounts
  
  scenarios-pathfilter:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-scenario-pathfilter

  scenarios-tendermint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-scenario-tendermint

  scenarios-stride:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: checkout relayer
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: interchaintest
        run: make interchaintest-scenario-stride
