name: TESTING - mtd to ibc integration

on: [push]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    # Install and setup go
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    # setup docker
    - name: Set up Docker 19.03
      run: |
        sudo apt-get update -y
        sudo apt-get remove docker docker-engine docker.io
        sudo apt install docker.io
        sudo systemctl start docker

    # checkout relayer
    - name: checkout relayer
      uses: actions/checkout@v2

    # build cache
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    # run tests
    - name: run mtd tests
      run: make test-mtd
